a,b = map(int,raw_input().split())
print str(a)+'+'+str(b)+'='+str(a+b)
print str(a)+'-'+str(b)+'='+str(a-b)
print str(a)+'*'+str(b)+'='+str(a*b)
print str(a)+'/'+str(b)+'='+str(a/b)
print str(a)+'%'+str(b)+'='+str(a%b)
